// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLMnmS87XLO4Ff0EvmlB3Hd32kPkOq51A',
    appId: '1:363272512420:web:0e8893eeaac595ef829731',
    messagingSenderId: '363272512420',
    projectId: 'gas-sensor-befe7',
    authDomain: 'gas-sensor-befe7.firebaseapp.com',
    databaseURL: 'https://gas-sensor-befe7-default-rtdb.firebaseio.com',
    storageBucket: 'gas-sensor-befe7.firebasestorage.app',
    measurementId: 'G-YHWZJLK4HL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfrfwY-zzbmHoymP3pVqvsPpXMLfuH0Vc',
    appId: '1:363272512420:android:4e0389d4f73c11f0829731',
    messagingSenderId: '363272512420',
    projectId: 'gas-sensor-befe7',
    databaseURL: 'https://gas-sensor-befe7-default-rtdb.firebaseio.com',
    storageBucket: 'gas-sensor-befe7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnsJm71bayc1FBeKFsJrqZewgfIwxFv94',
    appId: '1:363272512420:ios:63ccac6b0bc287eb829731',
    messagingSenderId: '363272512420',
    projectId: 'gas-sensor-befe7',
    databaseURL: 'https://gas-sensor-befe7-default-rtdb.firebaseio.com',
    storageBucket: 'gas-sensor-befe7.firebasestorage.app',
    iosBundleId: 'com.example.gasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnsJm71bayc1FBeKFsJrqZewgfIwxFv94',
    appId: '1:363272512420:ios:63ccac6b0bc287eb829731',
    messagingSenderId: '363272512420',
    projectId: 'gas-sensor-befe7',
    databaseURL: 'https://gas-sensor-befe7-default-rtdb.firebaseio.com',
    storageBucket: 'gas-sensor-befe7.firebasestorage.app',
    iosBundleId: 'com.example.gasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLMnmS87XLO4Ff0EvmlB3Hd32kPkOq51A',
    appId: '1:363272512420:web:1dcfe7393c3bb2ae829731',
    messagingSenderId: '363272512420',
    projectId: 'gas-sensor-befe7',
    authDomain: 'gas-sensor-befe7.firebaseapp.com',
    databaseURL: 'https://gas-sensor-befe7-default-rtdb.firebaseio.com',
    storageBucket: 'gas-sensor-befe7.firebasestorage.app',
    measurementId: 'G-SW8TK5RR1M',
  );
}
